spring:


  profiles:
    active: local
  application:
    name: sample-dynamodb
  cloud:
    aws:
      s3:
        endpoint: http://localhost:4566
      dynamodb:
        endpoint: http://localhost:4566
